#include "token.h"

/* names of tokens for display (space padding ensures neat formatting)*/
const char *tokennames[] = {
    // "Error       ",
    "Assign      ",
    "Semicolon   ",
    "Comma       ",
    "LeftParen   ",
    "RightParen  ",
    "String      ",
    "Plus        ",
    "Minus       ",
    "Raise       ",
    "Equal       ",
    "LTEqual     ",
    "GTEqual     ",
    "NotEqual    ",
    "Identifier  ",
    "Number      ",
    "Multiply    ",
    "Divide      ",
    "Colon       ",
    "LessThan    ",
    "GreaterThan ",
    "PRINT       ",
    "IF          ",
    "ELSE        ",
    "ENDIF       ",
    "SQRT        ",
    "AND         ",
    "OR          ",
    "NOT         ",
    "EndOfFile   " 
};
